2014/06/06 11:44:14 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2000] mysqlnd cannot connect to MySQL 4.1+ using the old insecure authentication. Please use an administration tool to reset your password with the command SET PASSWORD = PASSWORD('your_existing_password'). This will store a new, and more secure, hash value in mysql.user. If this user is used in other scripts executed by PHP 5.2 or earlier you might need to remove the old-passwords flag from your my.cnf file' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:45:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:46:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:47:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No such file or directory' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:47:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No such file or directory' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:49:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:49:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:49:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No such file or directory' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:50:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:52:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:52:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:52:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:52:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:52:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:53:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:53:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:53:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No such file or directory' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:53:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No such file or directory' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:54:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:54:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)' in /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php:382
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /private/var/www/htdocs/erp.com/htdocs/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(387): CDbConnection->init()
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /private/var/www/htdocs/erp.com/htdocs/protected/models/YData.php(14): CModule->__get('db')
#5 /private/var/www/htdocs/erp.com/htdocs/protected/controllers/SiteController.php(25): YData::getNavData()
#6 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(359): SiteController->__construct('site', NULL)
#7 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(276): CWebApplication->createController('site/index')
#8 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index')
#9 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=site/index
---
2014/06/06 11:56:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in /private/var/www/htdocs/erp.com/htdocs/framework/web/CController.php:483
Stack trace:
#0 /private/var/www/htdocs/erp.com/htdocs/framework/web/CController.php(270): CController->missingAction('index')
#1 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(282): CController->run('index')
#2 /private/var/www/htdocs/erp.com/htdocs/framework/web/CWebApplication.php(141): CWebApplication->runController('admin/index')
#3 /private/var/www/htdocs/erp.com/htdocs/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /private/var/www/htdocs/erp.com/htdocs/index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=admin/index
---
